# Generated by Django 3.1 on 2020-08-10 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_firstname', models.CharField(max_length=100, verbose_name='Firstname')),
                ('author_lastname', models.CharField(max_length=100, verbose_name='Lastname')),
                ('author_joined_date', models.DateTimeField(auto_now=True, help_text='Joined: ')),
            ],
            options={
                'ordering': ['-author_joined_date'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_title', models.CharField(help_text='Tag: ', max_length=100)),
            ],
            options={
                'ordering': ['tag_title'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateTimeField(auto_now=True)),
                ('post_title', models.CharField(help_text='give a title for the post', max_length=100)),
                ('post_text', models.TextField(help_text='type here')),
                ('post_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.author')),
                ('post_tags', models.ManyToManyField(help_text='Select a genre for this book', to='api.Tag')),
            ],
            options={
                'ordering': ['-post_date', 'post_title'],
            },
        ),
    ]
